GET http://localhost:8086/users/?id=1
Accept: application/json

###

GET http://localhost:8086/users/nurzybrs
Accept: application/json

###

POST http://localhost:8085/users/
Content-Type: application/json

{
  "nickname": "2",
  "email": "2",
  "password" : "2"
}

###

POST http://localhost:8086/locations/
Content-Type: application/json

{
  "name": "name",
  "address": "somepaasword",
  "coordinates": "ddd"
}

###

POST http://localhost:8085/persons
Content-Type: application/json

{
  "email": "someemail2"
}

###

GET http://localhost:8085/locations/all
Accept: application/json


###

POST http://localhost:8085/events
Content-Type: application/json

{
  "location": {
    "id": "186"
  },
  "organiser": {
    "id": 1
  },
  "name": "4",
  "description": "4",
  "date": "2002-05-01",
  "time": "01:01:01",
  "capacity": 1
}



###

POST http://localhost:8085/users/login
Content-Type: application/json

{
  "nickname": "nurazybr",
  "password": "2323"
}

###

GET http://localhost:8085/locations/186
Content-Type: application/json

###


GET http://localhost:8085/users/matvey/events
Content-Type: application/json


###

POST http://localhost:8085/invitations/send
Content-Type: application/json

{
  "sender_id": 1,
  "recipient_email": "matsnev2001@yandex.ru"
}
###


GET https://app-oneplan-221011202557.azurewebsites.net/invitations/3
Content-Type: application/json
###


GET https://app-oneplan-221011202557.azurewebsites.net/invitations/user/1
Content-Type: application/json
###


GET  https://app-oneplan-221011202557.azurewebsites.net/invitations/users/nickname/{{nickname}}
Content-Type: application/json
###


GET https://app-oneplan-221011202557.azurewebsites.net/invitations/user/nickname/1
Content-Type: application/json
###


GET http://localhost:8085/friends/user/nick
Content-Type: application/json

###


GET http://localhost:8085/users/all
Content-Type: application/json
###


GET https://app-oneplan-221011202557.azurewebsites.net/users/all
Content-Type: application/json
###

POST http://localhost:8085/friends/create
Content-Type: application/json

{
  "email": "2@22.2",
  "userId": 3
}
###
POST http://localhost:8085/event-invites/create
Content-Type: application/json

{
  "recipientEmail": "test@test.com",
  "sender": 1,
  "eventModel": 4,
  "status": 0
}
###


GET http://localhost:8085/event-invites/matsnev2001@yandex.ru
###


GET http://localhost:8085/event-invites/nickname/nick
###


GET http://localhost:8085/event-invites/accept/test@test.com/3
###


GET http://localhost:8085/event-invites/invites/nick/pending


###
DELETE  http://localhost:8085/events/4
###


GET http://localhost:8085/event-invites/sender/nickname/nick

###


POST http://localhost:8085/friends/update/37
Content-Type: application/json

{
  "id": 37,
  "email": "my@friend.com",
  "nickname": "my friend 1"
}
###


GET http://localhost:8085/friends/get/37

###


GET http://localhost:8085/friends/user/nick


###


GET http://localhost:8085/event-invites/delete/


###


GET http://localhost:8085/event-invites/get-invited-to-event/8
###


GET http://localhost:8085/event-invites/accept/matsnev2001@yandex.ru/8
###


GET http://localhost:8085/users/verify/matsnnik@fit.cvut.cz
###


POST http://localhost:8085/users/send-password-email
Content-Type: application/json

{
  "email": "matsnev2001@yandex.ru"
}